# Goal of the ETL Lesson

The main goal of this ETL pipelines lesson is to take the [World Bank Project data set](https://datacatalog.worldbank.org/dataset/world-bank-projects-operations) and merge this data with the [World Bank indicator data](https://data.worldbank.org/indicator/SP.POP.TOTL). Then you'll load the merged data into a database.

In the process, you'll need to transform these data sets in different ways. And finally, you'll code an ETL pipeline to extract, transform, and load the data all in one step.

# Extracting data from a csv file

The first step in an ETL pipeline is extraction. Data comes in all types of different formats, and you'll practice extracting data from csv files, JSON files, XML files, SQL databases, and the web.

In this first exercise, you'll practice extracting data from a CSV file and then navigating through the results. You'll see that extracting data is not always a straight-forward process.

This exercise contains a series of coding questions for you to solve. If you get stuck, there is a solution file called 1_csv_exercise_solution.ipynb. You can find this solution file by going to File->Open and then clicking on the file name.

# Part 1 projects_data.csv

You'll be using the following csv files:
* projects_data.csv
* population_data.csv

As a first step, try importing the projects data using the pandas [read_csv method](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_csv.html). The file path is just '../data/projects_data.csv'. You can see the file if you click on File->Open in the workspace and open the data folder.

In [46]:
# TODO: import the projects_data.csv file using the pandas library
# Store the results in the df_projects variable
import pandas as pd
url_projects = 'https://s3.us-east-2.amazonaws.com/d5mit.co.za/Notebooks_Data/Udacity_ETL/projects_data.csv'
url_population = 'https://s3.us-east-2.amazonaws.com/d5mit.co.za/Notebooks_Data/Udacity_ETL/population_data.csv'
# url_projects = 'Data/projects_data.csv'
# url_population = 'Data/population_data.csv'

df_projects = pd.read_csv(url_projects)

/Users/d5mit/.conda/envs/Udacity_ETL/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3145: DtypeWarning: Columns (44) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

Did you get a DType warning? Read about what this warning is in the [pandas documentation](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.errors.DtypeWarning.html).

Pandas tries to figure out programatically the data type of each column (integer, float, boolean, string). In this case, pandas could not automatically figure out the data type. That is because some columns have more than one possible data types. In other words, this data is messy.

You can use the dtype option to specify the data type of each column. Because there are so many columns in this data set, you can set all columns to be strings at least for now.

Try reading in the data set again using the read_csv() method. This time, also use the option dtype=str so that pandas treats everything like a string.

In [47]:
# TODO: Read in the projects_data.csv file using the read_csv method 
# and dtype = str option
# df_projects = pd.read_csv('projects_data.csv')

df_projects = pd.read_csv(url_projects, dtype=str)

In [48]:
# Run the cell below to see what the data looks like
df_projects.head()

,id,regionname,countryname,prodline,lendinginstr,lendinginstrtype,envassesmentcategorycode,supplementprojectflg,productlinetype,projectstatusdisplay,...,mjtheme3name,mjtheme4name,mjtheme5name,location,GeoLocID,GeoLocName,Latitude,Longitude,Country,Unnamed: 56
0,P162228,Other,World;World,RE,Investment Project Financing,IN,C,N,L,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,P163962,Africa,Democratic Republic of the Congo;Democratic Re...,PE,Investment Project Financing,IN,B,N,L,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,P167672,South Asia,People's Republic of Bangladesh;People's Repub...,PE,Investment Project Financing,IN,NaN,Y,L,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,P158768,South Asia,Islamic Republic of Afghanistan;Islamic Repu...,PE,Investment Project Financing,IN,A,N,L,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,P161364,Africa,Federal Republic of Nigeria;Federal Republic o...,PE,Investment Project Financing,IN,B,N,L,Active,...,NaN,NaN,NaN,0002327546!$!Ogun State!$!7!$!3.58333!$!NG;000...,0002327546;0002328925;0002565340;0002565343;00...,Ogun State;Niger State;Abia State;Edo;Kebbi St...,7;10;5.41667;6.5;11.5;8,3.58333;6;7.5;6;4;10.5,NG;NG;NG;NG;NG;NG,NaN

In [49]:
# TODO: count the number of null values in the data set
# HINT: use the isnull() and sum() methods

# df_projects.head()
df_projects.notnull().sum()

id                          18248
regionname                  18248
countryname                 18248
prodline                    18248
lendinginstr                18002
lendinginstrtype            18002
envassesmentcategorycode    12437
supplementprojectflg        18195
productlinetype             18248
projectstatusdisplay        18244
status                      18244
project_name                18248
boardapprovaldate           16744
board_approval_month        16744
closingdate                 14899
lendprojectcost             18123
ibrdcommamt                 18248
idacommamt                  18248
totalamt                    18248
grantamt                    18248
borrower                    12329
impagency                   12151
url                         18248
projectdoc                      0
majorsector_percent             0
sector1                     18248
sector2                      9527
sector3                      6487
sector4                      4376
sector5                      2713
sector                      17610
mjsector1                       0
mjsector2                       0
mjsector3                       0
mjsector4                       0
mjsector5                       0
mjsector                    17610
theme1                      18248
theme2                       9853
theme3                       7484
theme4                       5234
theme5                       2928
theme                           0
goal                        12133
financier                    7060
mjtheme1name                    0
mjtheme2name                    0
mjtheme3name                    0
mjtheme4name                    0
mjtheme5name                    0
location                     4326
GeoLocID                     4326
GeoLocName                   4325
Latitude                     4326
Longitude                    4326
Country                      4203
Unnamed: 56                     0
dtype: int64

Notice that the number 18248 shows up multiple times. There is also a countryname column with 0 missing values and a Country column with 14045 missing values. This data set clearly has some issues that will need to be solved in the transform part of the pipeline.

Next, output the shape of the data frame.

In [50]:
# TODO: output the shape of the data frame
df_projects.shape

(18248, 57)

There are 18248 rows in this data set. Considering many columns had 18248 NaN values, many columns in the data set are filled completely with NaN values.

# Part 2 population_data.csv

Next, use the pandas read_csv method to read in the population_data.csv file. The path to this file is "../data/population_data.csv". When you try to read in this data set using pandas, you'll get an error because there is something wrong with the data.

In [51]:
# TODO: read in the population_data.csv file using the read_csv() method
# Put the results in a variable called df_population

df_population = pd.read_csv(url_population)

ParserError: Error tokenizing data. C error: Expected 3 fields in line 5, saw 63

There is something wrong with this data set. You should see an error that says "expected 3 fields in line 5, saw 63". What might have happened? Try printing out the first few lines of the data file to see what the issue might be.

In [52]:
# TODO: Print out the first 10 lines of the data set, line by line.
# HINT: You can't use the read_csv method from pandas
# HINT: to do this manually, you'll need to use pure Python
# HINT: the open(), readline(), and close() methods should be helpful
# HINT: Use a for loop

file_population = open(url_population, "rt")

i = 0 
for i in range(100):
    file_line = file_population.readline()
    print(file_line)


# Close opend file
file_population.close()

﻿"Data Source","World Development Indicators",



"Last Updated Date","2018-06-28",



"Country Name","Country Code","Indicator Name","Indicator Code","1960","1961","1962","1963","1964","1965","1966","1967","1968","1969","1970","1971","1972","1973","1974","1975","1976","1977","1978","1979","1980","1981","1982","1983","1984","1985","1986","1987","1988","1989","1990","1991","1992","1993","1994","1995","1996","1997","1998","1999","2000","2001","2002","2003","2004","2005","2006","2007","2008","2009","2010","2011","2012","2013","2014","2015","2016","2017",

"Aruba","ABW","Population, total","SP.POP.TOTL","54211","55438","56225","56695","57032","57360","57715","58055","58386","58726","59063","59440","59840","60243","60528","60657","60586","60366","60103","59980","60096","60567","61345","62201","62836","63026","62644","61833","61079","61032","62149","64622","68235","72504","76700","80324","83200","85451","87277","89005","90853","92898","94992","97017","98737","100031","100832","101220","101353","101453","101669","102053","102577","103187","103795","104341","104822","105264",

"Afghanistan","AFG","Population, total","SP.POP.TOTL","8996351","9166764","9345868","9533954","9731361","9938414","10152331","10372630","10604346","10854428","11126123","11417825","11721940","12027822","12321541","12590286","12840299","13067538","13237734","13306695","13248370","13053954","12749645","12389269","12047115","11783050","11601041","11502761","11540888","11777609","12249114","12993657","13981231","15095099","16172719","17099541","17822884","18381605","18863999","19403676","20093756","20966463","21979923","23064851","24118979","25070798","25893450","26616792","27294031","28004331","28803167","29708599","30696958","31731688","32758020","33736494","34656032","35530081",

"Angola","AGO","Population, total","SP.POP.TOTL","5643182","5753024","5866061","5980417","6093321","6203299","6309770","6414995","6523791","6642632","6776381","6927269","7094834","7277960","7474338","7682479","7900997","8130988","8376147","8641521","8929900","9244507","9582156","9931562","10277321","10609042","10921037","11218268","11513968","11827237","12171441","12553446","12968345","13403734","13841301","14268994","14682284","15088981","15504318","15949766","16440924","16983266","17572649","18203369","18865716","19552542","20262399","20997687","21759420","22549547","23369131","24218565","25096150","25998340","26920466","27859305","28813463","29784193",

"Albania","ALB","Population, total","SP.POP.TOTL","1608800","1659800","1711319","1762621","1814135","1864791","1914573","1965598","2022272","2081695","2135479","2187853","2243126","2296752","2350124","2404831","2458526","2513546","2566266","2617832","2671997","2726056","2784278","2843960","2904429","2964762","3022635","3083605","3142336","3227943","3286542","3266790","3247039","3227287","3207536","3187784","3168033","3148281","3128530","3108778","3089027","3060173","3051010","3039616","3026939","3011487","2992547","2970017","2947314","2927519","2913021","2905195","2900401","2895092","2889104","2880703","2876101","2873457",

"Andorra","AND","Population, total","SP.POP.TOTL","13411","14375","15370","16412","17469","18549","19647","20758","21890","23058","24276","25559","26892","28232","29520","30705","31777","32771","33737","34818","36067","37500","39114","40867","42706","44600","46517","48455","50434","52448","54509","56671","58888","60971","62677","63850","64360","64327","64142","64370","65390","67341","70049","73182","76244","78867","80991","82683","83861","84462","84449","83751","82431","80788","79223","78014","77281","76965",

"Arab World","ARB","Population, total","SP.POP.TOTL","92490932","95044497","97682294","100411076","103239902","106174988","109230593","112406932","115680165","119016542","122398374","125807419","129269375","132863416","136696761","140843298","145332378","150133054","155183724","160392488","165689490","171051950","176490084","182005827","187610756","193310301","199093767","204942549","210844771","216787402","224735446","230829868","235037179","241286091","247435930","255029671","260843462","266575075","272235146","277962869","283832016","289850357","296026575","302434519","309162029","316264728","323773264","331653797","339825483","348145094","356508908","364895878","373306993","381702086","390043028","398304960","406452690","414491886",

"United Arab Emirates","ARE","Population, total","SP.POP.TOTL","92634","101078","112472","125566","138529","150362","160481","170283","183194","203820","235499","278808","332760","397174","471364","554324","646943","748117","852262","952040","1042384","1120900","1189545","1253060","1318478","1391052","1472218","1560718","1655849","1756043","1860174","1970026","2086639","2207405","2328686","2448820","2571020","2700010","2838145","2988162","3154925","3326032","3507232","3741932","4087931","4579562","5242032","6044067","6894278","7666393","8270684","8672475","8900453","9006263","9070867","9154302","9269612","9400145",

"Argentina","ARG","Population, total","SP.POP.TOTL","20619075","20953077","21287682","21621840","21953929","22283390","22608748","22932203","23261278","23605987","23973058","24366439","24782949","25213388","25644506","26066975","26477152","26878565","27277741","27684534","28105888","28543364","28993987","29454738","29920904","30388783","30857244","31326473","31795517","32263561","32729739","33193918","33655151","34110917","34558115","34994814","35419682","35833969","36241590","36648068","37057452","37471509","37889370","38309379","38728696","39145488","39558890","39970224","40382389","40799407","41223889","41656879","42096739","42539925","42981515","43417765","43847430","44271041",

"Armenia","ARM","Population, total","SP.POP.TOTL","1874120","1941491","2009526","2077575","2144998","2211316","2276031","2339124","2401140","2462925","2525065","2587706","2650484","2712781","2773747","2832757","2889579","2944379","2997411","3049105","3099751","3148092","3193686","3238594","3285595","3335935","3392256","3451942","3504651","3536469","3538165","3505251","3442810","3363098","3283660","3217342","3168215","3133086","3108684","3089017","3069588","3050655","3033897","3017806","3000612","2981259","2958500","2933056","2908220","2888584","2877311","2875581","2881922","2893509","2906220","2916950","2924816","2930450",

"American Samoa","ASM","Population, total","SP.POP.TOTL","20013","20486","21117","21882","22698","23520","24321","25116","25885","26614","27292","27916","28492","29014","29488","29932","30321","30689","31102","31673","32457","33493","34738","36160","37688","39241","40837","42450","44047","45593","47038","48375","49593","50720","51803","52868","53929","54941","55901","56770","57521","58175","58731","59117","59264","59118","58650","57903","57030","56227","55637","55320","55230","55307","55437","55537","55599","55641",

"Antigua and Barbuda","ATG","Population, total","SP.POP.TOTL","55339","56144","57144","58294","59524","60781","62059","63360","64655","65910","67098","68188","69176","70066","70878","71609","72285","72875","73324","73528","73442","73066","72448","71639","70725","69782","68809","67845","67058","66627","66696","67307","68427","69938","71719","73619","75628","77739","79851","81831","83584","85057","86266","87293","88257","89253","90301","91381","92478","93581","94661","95719","96777","97824","98875","99923","100963","102012",

"Australia","AUS","Population, total","SP.POP.TOTL","10276477","10483000","10742000","10950000","11167000","11388000","11651000","11799000","12009000","12263000","12507000","12937000","13177000","13380000","13723000","13893000","14033000","14192000","14358000","14514000","14692000","14927000","15178000","15369000","15544000","15758000","16018400","16263900","16532200","16814400","17065100","17284000","17495000","17667000","17855000","18072000","18311000","18517000","18711000","18926000","19153000","19413000","19651400","19895400","20127400","20394800","20697900","20827600","21249200","21691700","22031750","22340024","22742475","23145901","23504138","23850784","24210809","24598933",

"Austria","AUT","Population, total","SP.POP.TOTL","7047539","7086299","7129864","7175811","7223801","7270889","7322066","7376998","7415403","7441055","7467086","7500482","7544201","7586115","7599038","7578903","7565525","7568430","7562305","7549425","7549433","7568710","7574140","7561910","7561434","7564985","7569794","7574586","7585317","7619567","7677850","7754891","7840709","7905633","7936118","7948278","7959017","7968041","7976789","7992324","8011566","8042293","8081957","8121423","8171966","8227829","8268641","8295487","8321496","8343323","8363404","8391643","8429991","8479823","8546356","8642699","8736668","8809212",

"Azerbaijan","AZE","Population, total","SP.POP.TOTL","3895396","4030320","4171425","4315128","4456689","4592610","4721525","4843870","4960235","5071930","5180025","5284532","5385267","5483084","5579077","5674137","5768724","5863134","5957929","6053645","6150738","6249320","6349558","6452076","6557585","6666455","6778633","6893500","7010036","7126891","7159000","7271000","7382000","7495000","7597000","7685000","7763000","7838250","7913000","7982750","8048600","8111200","8171950","8234100","8306500","8391850","8484550","8581300","8763400","8947243","9054332","9173082","9295784","9416801","9535079","9649341","9757812","9862429",

"Burundi","BDI","Population, total","SP.POP.TOTL","2786106","2839666","2893669","2949926","3010859","3077876","3152723","3234023","3316233","3391753","3455606","3505391","3544047","3578490","3618585","3671494","3739659","3821194","3913768","4013310","4116817","4223195","4333386","4448728","4571292","4702066","4841565","4987736","5135956","5280024","5415415","5542048","5661139","5771398","5871607","5962058","6041112","6112097","6186352","6278940","6400706","6555829","6741569","6953113","7182451","7423289","7675338","7939573","8212264","8489031","8766930","9043508","9319710","9600186","9891790","10199270","10524117","10864245",

"Belgium","BEL","Population, total","SP.POP.TOTL","9153489","9183948","9220578","9289770","9378113","9463667","9527807","9580991","9618756","9646032","9655549","9673162","9711115","9741720","9772419","9800700","9818227","9830358","9839534","9848382","9859242","9858982","9856303","9855520","9855372","9858308","9861823","9870234","9901664","9937697","9967379","10004486","10045158","10084475","10115603","10136811","10156637","10181245","10203008","10226419","10251250","10286570","10332785","10376133","10421137","10478617","10547958","10625700","10709973","10796493","10895586","11047744","11128246","11182817","11209057","11274196","11331422","11372068",

"Benin","BEN","Population, total","SP.POP.TOTL","2431622","2465867","2502896","2542859","2585965","2632356","2682159","2735307","2791590","2850661","2912340","2976572","3043567","3113675","3187412","3265165","3347173","3433439","3523938","3618526","3717165","3820128","3927714","4039949","4156819","4278501","4404506","4535263","4672852","4820016","4978496","5149499","5331803","5521763","5714220","5905558","6094259","6281639","6470265","6664098","6865951","7076733","7295394","7520555","7750004","7982225","8216896","8454791","8696916","8944706","9199259","9460802","9729160","10004451","10286712","10575952","10872298","11175692",

"Burkina Faso","BFA","Population, total","SP.POP.TOTL","4829288","4894580","4960326","5027821","5098890","5174870","5256363","5343019","5434041","5528174","5624600","5723381","5825173","5930483","6040041","6154545","6274037","6398935","6530819","6671656","6822843","6985160","7158255","7340905","7531242","7727907","7930694","8140073","8356305","8579823","8811034","9050084","9297113","9552476","9816588","10089878","10372745","10665546","10968724","11282701","11607942","11944587","12293100","12654621","13030569","13421930","13829177","14252021","14689726","15141099","15605217","16081904","16571216","17072723","17585977","18110624","18646433","19193382",

"Bangladesh","BGD","Population, total","SP.POP.TOTL","48199747","49592802","51030137","52532417","54129100","55834038","57672990","59620669","61579473","63417394","65047770","66424744","67597470","68691185","69884420","71305923","72999136","74925896","77033846","79236776","81470860","83721268","86007331","88338242","90732362","93199865","95742431","98343809","100975321","103599232","106188642","108727432","111221938","113695139","116182267","118706871","121269645","123854640","126447965","129029691","131581243","134107160","136600667","139019001","141307489","143431101","145368004","147139191","148805814","150454708","152149102","153911916","155727053","157571292","159405279","161200886","162951560","164669751",

"Bulgaria","BGR","Population, total","SP.POP.TOTL","7867374","7943118","8012946","8078145","8144340","8204168","8258057","8310226","8369603","8434172","8489574","8536395","8576200","8620967","8678745","8720742","8758599","8804183","8814032","8825940","8861535","8891117","8917457","8939738","8960679","8960547","8958171","8971359","8981446","8876972","8718289","8632367","8540164","8472313","8443591","8406067","8362826","8312068","8256786","8210624","8170172","8009142","7837161","7775327","7716860","7658972","7601022","7545338","7492561","7444443","7395599","7348328","7305888","7265115","7223938","7177991","7127822","7075991",

"Bahrain","BHR","Population, total","SP.POP.TOTL","162427","167894","173144","178140","182887","187431","191780","196063","200653","206043","212605","220312","229155","239527","251911","266543","283752","303175","323473","342798","359888","374120","385950","396454","407227","419430","433482","448973","465202","481090","495931","509765","523087","536213","549588","563699","578668","594930","613702","636545","664614","697549","735148","778711","829848","889168","958414","1035891","1114590","1185029","1240862","1278269","1300217","1315411","1336397","1371855","1425171","1492584",

"Bahamas, The","BHS","Population, total","SP.POP.TOTL","109528","115108","121083","127333","133698","140054","146366","152609","158627","164248","169354","173863","177839","181488","185099","188882","192902","197111","201513","206032","210661","215396","220275","225187","230015","234687","239131","243393","247579","251849","256336","261116","266134","271165","275895","280150","283790","286970","290060","293572","297890","303135","309157","315746","322526","329249","335830","342328","348676","354856","360832","366568","372039","377240","382169","386838","391232","395361",

"Bosnia and Herzegovina","BIH","Population, total","SP.POP.TOTL","3225668","3288602","3353226","3417574","3478995","3535640","3586634","3632669","3675452","3717466","3760527","3805285","3851151","3897255","3942223","3985103","4025265","4063191","4100350","4138819","4179855","4222511","4265310","4308106","4350746","4392130","4435504","4478519","4508056","4506653","4463422","4371603","4239154","4087999","3948816","3843712","3780378","3752431","3750485","3759118","3766706","3771284","3775807","3779247","3781287","3781530","3779468","3774000","3763599","3746561","3722084","3688865","3648200","3604999","3566002","3535961","3516816","3507017",

"Belarus","BLR","Population, total","SP.POP.TOTL","8198000","8271216","8351928","8437232","8524224","8610000","8696496","8785648","8874552","8960304","9040000","9115576","9188968","9257272","9317584","9367000","9411000","9463000","9525000","9584000","9643000","9710000","9776000","9843000","9910000","9975000","10043000","10111000","10140000","10170000","10189000","10194000","10216000","10239000","10227000","10194000","10160000","10117000","10069000","10026738","9979610","9928549","9865548","9796749","9730146","9663915","9604924","9560953","9527985","9506765","9490583","9473172","9464495","9465997","9474511","9489616","9501534","9507875",

"Belize","BLZ","Population, total","SP.POP.TOTL","92064","94703","97384","100164","103069","106119","109347","112692","116061","119261","122182","124793","127150","129294","131307","133260","135147","136989","138965","141305","144155","147566","151500","155822","160347","164921","169568","174320","179028","183469","187552","191126","194317","197616","201674","206963","213676","221606","230284","239026","247315","254984","262206","269130","276089","283277","290747","298407","306165","313929","321608","329192","336701","344181","351694","359288","366954","374681",

"Bermuda","BMU","Population, total","SP.POP.TOTL","44400","45500","46600","47700","48900","50100","51000","52000","53000","54000","55000","54600","54200","53800","53400","53000","53200","53400","53600","53800","54670","55050","55449","55930","56423","56898","57382","57849","58347","58841","59326","59021","58595","58910","59320","59746","60129","60497","60943","61285","61833","62504","62912","63325","63740","64154","64523","64888","65273","65636","65124","64564","64798","65001","65139","65239","65341","65441",

"Bolivia","BOL","Population, total","SP.POP.TOTL","3693449","3764813","3838097","3913395","3990857","4070590","4152668","4237125","4324064","4413590","4505778","4600591","4698083","4798509","4902168","5009257","5119833","5233677","5350322","5469123","5589575","5711599","5835182","5959960","6085496","6211550","6337893","6464732","6592787","6723046","6856244","6992521","7131707","7273825","7418861","7566714","7717443","7870855","8026254","8182712","8339512","8496375","8653345","8810420","8967741","9125409","9283334","9441444","9599855","9758748","9918242","10078343","10239004","10400264","10562159","10724705","10887882","11051600",

"Brazil","BRA","Population, total","SP.POP.TOTL","72207554","74351763","76573248","78854019","81168654","83498020","85837799","88191378","90557064","92935072","95326793","97728961","100143598","102584278","105069367","107612100","110213082","112867867","115577669","118342626","121159761","124030908","126947365","129882321","132800684","135676281","138499464","141273488","144001542","146691981","149352145","151976577","154564278","157132682","159705123","162296612","164913306","167545164","170170640","172759243","175287587","177750670","180151021","182482149","184738458","186917361","189012412","191026637","192979029","194895996","196796269","198686688","200560983","202408632","204213133","205962108","207652865","209288278",

"Barbados","BRB","Population, total","SP.POP.TOTL","230939","231678","232586","233587","234547","235374","236044","236621","237199","237913","238848","240035","241441","242976","244539","246034","247444","248784","250032","251177","252194","253080","253841","254518","255193","255924","256736","257611","258527","259458","260374","261275","262184","263089","264015","264959","265942","266945","267950","268922","269847","270685","271478","272258","273091","274009","275039","276150","277319","278470","279569","280601","281585","282509","283385","284217","284996","285719",

"Brunei Darussalam","BRN","Population, total","SP.POP.TOTL","81745","85596","89516","93576","97848","102425","107316","112494","117950","123653","129583","135726","142073","148560","155109","161671","168224","174773","181257","187656","193949","200085","206128","212136","218227","224512","230972","237622","244458","251514","258785","266274","273963","281751","289525","297192","304699","312038","319222","326289","333241","340117","346867","353389","359523","365158","370250","374864","379252","383772","388662","394013","399748","405716","411704","417542","423196","428697",

"Bhutan","BTN","Population, total","SP.POP.TOTL","223288","228918","234706","240778","247325","254464","262244","270622","279515","288774","298301","308053","318045","328312","338943","349982","361455","373324","385384","397390","409172","420380","431050","441847","453720","467178","482952","500437","517273","530257","537280","537284","531525","523117","516503","514877","519282","528754","542155","557543","573416","589600","606399","623434","640282","656639","672228","686958","700950","714458","727641","740510","752967","764961","776448","787386","797765","807610",


The first four lines in the file are not properly formatted and don't contain data. Next, read in the data using the read_csv method. But this time, use the skiprows option.

In [59]:
# TODO: read in population data skipping the first four rows
# Put the results in a variable called df_population

df_population = pd.read_csv(url_population, dtype=str, skiprows=4)

In [60]:
# Run this cell to see what the data looks like
df_population.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,Unnamed: 62
0,Aruba,ABW,"Population, total",SP.POP.TOTL,54211,55438,56225,56695,57032,57360,...,101453,101669,102053,102577,103187,103795,104341,104822,105264,NaN
1,Afghanistan,AFG,"Population, total",SP.POP.TOTL,8996351,9166764,9345868,9533954,9731361,9938414,...,28004331,28803167,29708599,30696958,31731688,32758020,33736494,34656032,35530081,NaN
2,Angola,AGO,"Population, total",SP.POP.TOTL,5643182,5753024,5866061,5980417,6093321,6203299,...,22549547,23369131,24218565,25096150,25998340,26920466,27859305,28813463,29784193,NaN
3,Albania,ALB,"Population, total",SP.POP.TOTL,1608800,1659800,1711319,1762621,1814135,1864791,...,2927519,2913021,2905195,2900401,2895092,2889104,2880703,2876101,2873457,NaN
4,Andorra,AND,"Population, total",SP.POP.TOTL,13411,14375,15370,16412,17469,18549,...,84462,84449,83751,82431,80788,79223,78014,77281,76965,NaN

Make sure to scroll over to see what the last column looks like. That last column, called 'Unnamed: 62', doesn't look very useful and is filled with NaN values.

In [66]:
# TODO: Count the number of null values in each column
# print(df_population.isnan().sum())

df_population.isna().sum()[0:50]

Country Name      0
Country Code      0
Indicator Name    0
Indicator Code    0
1960              4
1961              4
1962              4
1963              4
1964              4
1965              4
1966              4
1967              4
1968              4
1969              4
1970              4
1971              4
1972              4
1973              4
1974              4
1975              4
1976              4
1977              4
1978              4
1979              4
1980              4
1981              4
1982              4
1983              4
1984              4
1985              4
1986              4
1987              4
1988              4
1989              4
1990              2
1991              2
1992              3
1993              3
1994              3
1995              2
1996              2
1997              2
1998              1
1999              1
2000              1
2001              1
2002              1
2003              1
2004              1
2005              1
dtype: int64

It looks like every year column has at least one NaN value.

In [70]:
# TODO: Count the number of null values in each row
# HINT: In the sum method, use axis=1

df_population.isnull().sum(axis=1)[0:40]

0     1
1     1
2     1
3     1
4     1
5     1
6     1
7     1
8     1
9     1
10    1
11    1
12    1
13    1
14    1
15    1
16    1
17    1
18    1
19    1
20    1
21    1
22    1
23    1
24    1
25    1
26    1
27    1
28    1
29    1
30    1
31    1
32    1
33    1
34    1
35    1
36    1
37    1
38    1
39    1
dtype: int64

And it looks like almost every row has only one null value. That is probably from the 'Unnamed: 62' column that doesn't have any relevant information in it. Next, drop the 'Unnamed: 62' column from the data frame.

In [73]:
# TODO: drop the 'Unnamed: 62' column from the data frame, 
# and save the results in the df_population variable

# df_population = df_population.drop('Unnamed: 62')

df_population = df_population.drop(columns=['Unnamed: 62'])

KeyError: "['Unnamed: 62'] not found in axis"

In [74]:
df_population.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,Aruba,ABW,"Population, total",SP.POP.TOTL,54211,55438,56225,56695,57032,57360,...,101353,101453,101669,102053,102577,103187,103795,104341,104822,105264
1,Afghanistan,AFG,"Population, total",SP.POP.TOTL,8996351,9166764,9345868,9533954,9731361,9938414,...,27294031,28004331,28803167,29708599,30696958,31731688,32758020,33736494,34656032,35530081
2,Angola,AGO,"Population, total",SP.POP.TOTL,5643182,5753024,5866061,5980417,6093321,6203299,...,21759420,22549547,23369131,24218565,25096150,25998340,26920466,27859305,28813463,29784193
3,Albania,ALB,"Population, total",SP.POP.TOTL,1608800,1659800,1711319,1762621,1814135,1864791,...,2947314,2927519,2913021,2905195,2900401,2895092,2889104,2880703,2876101,2873457
4,Andorra,AND,"Population, total",SP.POP.TOTL,13411,14375,15370,16412,17469,18549,...,83861,84462,84449,83751,82431,80788,79223,78014,77281,76965

In [75]:
# Run this code cell.  
# This code outputs any row that contains a null value
# The purpose is to see what rows contain null values now that 
#   'Unnamed: 62' was dropped from the data.
df_population[df_population.isnull().any(axis=1)]

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
67,Eritrea,ERI,"Population, total",SP.POP.TOTL,1397491,1432640,1469645,1508273,1548187,1589179,...,4232636,4310334,4390840,4474690,NaN,NaN,NaN,NaN,NaN,NaN
108,Not classified,INX,"Population, total",SP.POP.TOTL,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
125,Kuwait,KWT,"Population, total",SP.POP.TOTL,269618,301336,338296,379891,425235,473554,...,2652340,2818939,2998083,3191051,3395556,3598385,3782450,3935794,4052584,4136528
194,West Bank and Gaza,PSE,"Population, total",SP.POP.TOTL,NaN,NaN,NaN,NaN,NaN,NaN,...,3596688,3702218,3811102,3927051,4046901,4169506,4294682,4422143,4551566,4684777
212,Serbia,SRB,"Population, total",SP.POP.TOTL,NaN,NaN,NaN,NaN,NaN,NaN,...,7350222,7320807,7291436,7234099,7199077,7164132,7130576,7095383,7058322,7022268
223,Sint Maarten (Dutch part),SXM,"Population, total",SP.POP.TOTL,NaN,NaN,NaN,NaN,NaN,NaN,...,33964,34238,34056,33435,34640,36607,37685,38824,39969,41109

# Conclusion 

This population data doesn't look too bad. Only six rows have missing values. In the transformation part of the lesson, you'll have to deal with these missing values somehow.

If you would like to see the solution file for this exercise, go to File->Open and click on 1_csv_exercise_solution.ipynb.

In the next exercise, you'll practice extracting data json and xml files.